messages:
    grimoire-received: "<green>¡Has recibido un Grimorio de Despojo!</green>"
    grimoire-dropped: "<yellow>¡Tu inventario está lleno! El Grimorio de Despojo ha caído al suelo.</yellow>"
    config-reloaded: "<green>¡La configuración se ha recargado exitosamente!</green>"
    no-armor: "<red>{player} no está usando ninguna armadura!</red>"
    armor-stripped: "<green>¡Armadura despojada exitosamente de {player}!</green>"
    armor-removed: "<red>¡Tu armadura ha sido retirada por {player} usando un Grimorio de Despojo!</red>"
