name: StripGrimoire
version: "${version}"
main: com.spectrasonic.StripGrimoire.Main
api-version: "1.21"
authors: [Spectrasonic]
commands:
    stripgrimoire:
        aliases: [sg]
        permission: stripgrimoire.admin
permissions:
    stripgrimoire.command:
        default: op
